services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    restart: always

  backend:
    build:
      context: ./backend
    ports:
      - "5050:5050"
    restart: always