services:

  # PYTHON ARTICLE SCRAPER
  # ----------------------
  # scraper:
  #   build: ./backend
  #   depends_on:
  #     - clickhouse
  #   environment:
  #     - CLICKHOUSE_HOST=clickhouse
  #     - CLICKHOUSE_PORT=${CLICKHOUSE_PORT}
  #     - CLICKHOUSE_USER=${CLICKHOUSE_USER}
  #     - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}


  # DATABASE
  # --------
  clickhouse:
    image: clickhouse/clickhouse-server
    restart: always
    ports:
      - "${CLICKHOUSE_PORT_HTTP}:8123"
      - "${CLICKHOUSE_PORT_CONSOLE}:9000"
    environment:
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
    volumes:
      - clickhouse_data:/var/lib/clickhouse


  # FLASK API -> VUE FRONTEND
  # -------------------------
  api:
    build: ./backend
    container_name: flask-backend
    depends_on:
      - clickhouse
      - spark-master
    volumes:
      - ./backend:/app
      - ./jars:/opt/spark/jars
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - CLICKHOUSE_HOST=clickhouse
    ports:
      - "${FLASK_PORT}:5000"
    env_file:
      - .env
    


  # VUE-BASED FRONTEND
  # ------------------
  # frontend:
  #   build: ./frontend
  #   depends_on:
  #     - api
  #   environment:
  #     - VUE_APP_API_URL=http://api:${FLASK_PORT}
  #   ports:
  #     - "${VUE_PORT}:8080"


  # SPARK WORKERS
  # -------------
  spark-master:
    image: bitnami/spark:3.5.0
    environment:
      - SPARK_MODE=master
    ports:
      - "${SPARK_MASTER_PORT}:7077"
      - "${SPARK_UI_PORT}:8081"
    volumes:
      - ./jars:/opt/spark/jars


  spark-worker:
    image: bitnami/spark:3.5.0
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:${SPARK_MASTER_PORT}
    depends_on:
      - spark-master
    volumes:
      - ./jars:/opt/spark/jars
    


  # ML MODEL TRAINING / EDA
  # -----------------------
  # ml:
  #   build: ./ml
  #   depends_on:
  #     - clickhouse
  #   environment:
  #     - CLICKHOUSE_HOST=clickhouse


  jupyter:
    image: jupyter/pyspark-notebook
    ports:
      - "${JUPYTER_PORT}:8888"
    env_file:
      - .env
    volumes:
      - jupyter_data:/home/jovyan # Main data volume
      - ./notebooks:/home/jovyan/work
      - ./backend:/home/jovyan/backend
      - ./jars:/opt/spark/jars # Mirror the jars from the spark worker / master
    user: root
    environment:
      - NB_USER=jovyan
      - NB_UID=1000
      - NB_GID=100
    command: >
      bash -c "echo 'jovyan:password' | chpasswd &&
               echo 'jovyan ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers &&
               start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"


# MISC
# ----

volumes:
  clickhouse_data:
  jupyter_data: